sym16_simple_stock_homepage:
    path:     /
    defaults: { _controller: SYM16SimpleStockBundle:Default:index }

sym16_simple_stock_ilike:
    path:    /iLike/{dormir}
    defaults: {_controller: SYM16SimpleStockBundle:GODIPremierControleur:iLike}

sym16_simple_stock_produit:
    path:   /produit/{a1}/{a2}
    defaults: {_controller: SYM16SimpleStockBundle:GODIPremierControleur:produit}
    requirements:
       a1:   ^[0-9a-fA-F]-$
       a2:   ^[0-9a-fA-F]-$
